---
title: "NBES calculation in simulated data"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here we analyse the model runs created to explore the underlying mechanisms in the NBES paper.

## Model description
We simulated a five-species community using a continuous Lotka-Volterra model with temperature-dependent vital rates (Vasseur, 2020). In the model, the change of biomass for each species is described as 

dN_i/dt = N_i*r(T)* (1-(∑α_ij*N_j)/K(T)) 

where N_i is the species-specific biomass, The r is the intrinsic rate of natural increase, which is given by the difference between the birth rate (b_(0,i) )  and deathrate (d_(0,i)). K is the carrying capacity, α_(i,j) the competition strength between species i and species j, and N_j the biomass of species j.

The carrying capacity K of species i is given as 
K_i=r_mi/(β+δ)  (Vasseur, 2020; Eq 14.6)
where β and δ are the density dependent constants.

Temperature dependence was incorporated into the birth and death rate:
b_(0,i) (T)=abe^(-(T-b_(opt,i) )^2/s_i )
d_(0,i) (T)=ade^ziT (Vasseur, 2020; Eq 14.5)

where, a_ is an intercept, b_(opt,i)  is the temperature at which intrinsic growth rate is highest, s is the width of intrinsic growth rate, z is the slope of death rate and scales the effect of temperature (in °C) to mimic the Arrhenius relationship. Combining the birth rate temperature function and death rate temperature function gives the left-skewed shape common for temperature performance curves (Vasseur, 2020).


We created communities 5 species, that differ in their strength of interspecific competition and temperature optimum. The interspecific competition terms are drawn from a one-sided normal distribution α>0, so that all interactions were competitive with asymmetric interactions between any two species in the model. A higher value for α indicates a stronger effect by species i on species j, whereas a low value of α indicates a small effect of species i on species j. We varied interspecific competition terms by introducing differing standard deviations of competition values α_ij.

We simulated each of the species within the communities as monocultures and in combinations of 2-5 species. Each of the species assemblages was then exposed to a temperature increase (disturbance) and a control (undisturbed).  

## Settings
n = 5 species;  
repetitions = 20, 20 independent simulations for each scenario;  
time points = 150;  

Temp Min: 15 (minimum temperature in disturbance);  
Temp Max:20 (maximum temperature in disturbance);  
Temp Control: 17.5 (temperature for control run). 

We manipulated response diversity (RD) and species competition strength (alpha). Specifically, we tested three levels of competitiveness in our communities, that were drawn from a left-sided distribution, so that all interactions are competitive:   
sd = 0 - no interaction;   
sd = 0.25 intermediate interaction strength;   
sd = 0.5 high interaction strength;   

For response diversity, we manipulated the distribution of temperature optima within the community, by distributing them evenly along a chosen temperature gradient. For example, for high response diversity, Temperature optima ranged between 15-20 and thus were 15, 16, 17, 18, 19, 20 for species 1-5. Specificially, we tested:   
no RD: Topt of 15 and thus a negative effect;    
low RD: Topt ranging between 17-18 degree;  
intermed RD: Topt ranging between 16-19 degree;  
high RD: Topt ranging between 15-20 degree;  

We ran 20 independent simulations for each of the settings.  For analysis, we include only the first 100 time points before the system shows non-equlibrium/ chaotic dynamics
